# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf1891887a42e0d33ae2cc2d7911c79b31caa54d6f16b6a5fe163e6494aadb2ad89898ea243b5c852d82724cc34926369e53847f030ff7d0c957de611f3c1d3

test:
  secret_key_base: ac20b84a03415fc354c68b734a5e41b11bf7bb887d4f22c17dca7f9c96db992da5fd1c49475986c927ce2306ce18610699b1c1246f5f11fb0048c0ee52016270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
